name: sNewton4PDEOpt
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8.11
  - pip=20.2.4
  - fenics=2019.1.0
  - scipy=3.8.11
  - numpy=3.8.11
  - matplotlib=3.8.11
  - pip:
      - git+https://github.com/dolfin-adjoint/pyadjoint.git@2019.1.0
